SET NAMES gbk;

DROP TABLE IF EXISTS sync_user_full;
CREATE TABLE sync_user_full (
  name varchar(16) default NULL,
  mate varchar(16) default NULL,
  monicker varchar(16) default NULL,
  look int(11) default 0,
  face int(11) default 0,
  life int(11) default 0,
  power int(11) default 0,
  money int(11) default 0,
  money_saved int(11) default 0,
  repute int(11) default 0,
  level int(11) default 0,
  exp int(11) default 0,
  exp_smith int(11) default 0,
  exp_creative int(11) default 0,
  exp_medicine int(11) default 0,
  exp_steal int(11) default 0,
  physique int(11) default 0,
  stamina int(11) default 0,
  force int(11) default 0,
  speed int(11) default 0,
  degree int(11) default 0,
  recordx int(11) default 0,
  recordy int(11) default 0,
  recordmap_id int(11) default 0,
  metempsychosis int(11) default 0,
  deed int(11) default 0,
  additional_point int(11) default 0,
  task_mask int(11) default 0,
  pk_enable int(11) default 0,
  home_id int(11) default 0,
  syndicate_id int(11) default 0,
  pet_count int(11) default 0,
  petused_id int(11) default 0,
  pet0_id int(11) default 0,
  pet1_id int(11) default 0,
  pet2_id int(11) default 0,
  pet3_id int(11) default 0,
  pet4_id int(11) default 0,
  skill_count int(11) default 0,
  skill0_id int(11) default 0,
  skill1_id int(11) default 0,
  skill2_id int(11) default 0,
  skill3_id int(11) default 0,
  skill4_id int(11) default 0,
  skill5_id int(11) default 0,
  skill6_id int(11) default 0,
  skill7_id int(11) default 0,
  skill8_id int(11) default 0,
  skill9_id int(11) default 0,
  skill10_id int(11) default 0,
  weapon_id int(11) default 0,
  armor_id int(11) default 0,
  shoes_id int(11) default 0,
  treasure0_id int(11) default 0,
  treasure1_id int(11) default 0,
  account_id int(11) default 0,
  id int(11) NOT NULL default 0,
  degree_lev int(11) default 0,
  lockkey int(11) default 0,
  intellect int(11) default 0,
  quiz_point int(11) default 0,
  coin_money int(11) default 0,
  marriage int(11) default NULL,
  last_login int(11) default 0,
  snapshot_time int(10) NOT NULL default 0,
  PRIMARY KEY (id)
) ENGINE=MyISAM;
